version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: peluqueria_db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=peluqueria_canina
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
